version: '3.4'

services:
  mytasklist:
    image: mytasklist
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3080:3080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
