services:
  personal-data-server:
    image: personal-data-server
    container_name: personal-data-server
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /mnt/z/PersonalData/media:/usr/src/app/media
    environment:
      NODE_ENV: production
      PORT: 3080
      DB: 192.168.0.201
    restart: unless-stopped
    ports:
      - 3080:3080
    networks:
      - mongodb

networks:
  mongodb:
    external: true
